import Bot from "@/components/Bot";
import Container from "@/components/Container";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import ToastContainerBar from "@/provider/ToastContainerBar";
import "../styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Container>
          <Navbar />
          <ToastContainerBar />
          <Bot />
          {children}
          <Footer />
        </Container>
      </body>
    </html>
  );
}
